---
- name: Ansible Base
  hosts: all
  become: true

  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks:
        file: handlers/main.yml

  tasks:
    - name: Install common system packages like htop, ncdu and vim
      ansible.builtin.import_tasks:
        file: tasks/system_packages.yml
    - name: Configure hostname to match inventory
      ansible.builtin.import_tasks:
        file: tasks/hostname.yml
    - name: Set timezone according to iventory group
      ansible.builtin.import_tasks:
        file: tasks/timezone.yml
    - name: Harden SSHD config against the scary internet
      ansible.builtin.import_tasks:
        file: tasks/sshd_config.yml
    - name: Upload ssh_keys in files/ssh_keys/*.pub
      ansible.builtin.import_tasks:
        file: tasks/ssh_keys.yml
