---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Configure /etc/hosts to match hostname
  lineinfile:
    path: /etc/hosts
    regex: '^127.0.1.1'
    line: '127.0.1.1	{{ inventory_hostname }}'
